### ISSUE TITLE
https://github.com/netgroup-polito/frog4-configurable-vnf/tree/master/docker/generaic-configuration-image/vnf_template_library

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-configurable-vnf#1]
The above folder should be a submodule, and should be in the repo root

**Comment by ivanocerrato** [comment]
@DavideXX92 @piscoroma is this issue solved? 
The URL in the title does no longer exist.

**Comment by frisso** [comment]
@DavideXX92, @piscoroma: is this issue solved?
If so, please close it.

**Comment by DavideXX92** [comment]
Closed with commit [b717d4f](https://github.com/netgroup-polito/frog4-configurable-vnf/commit/b717d4f5928f32144910b5262a560e3970b1a741)
